package com.spring.simple.dao.objects;

import java.io.Serializable;
import java.util.Date;

public class MerchantPushLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.merchant_id
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.biz_no
     *
     * @mbggenerated
     */
    private String bizNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.org_biz_no
     *
     * @mbggenerated
     */
    private String orgBizNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.push_data_size
     *
     * @mbggenerated
     */
    private Long pushDataSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.success
     *
     * @mbggenerated
     */
    private String success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.success_code
     *
     * @mbggenerated
     */
    private String successCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.success_message
     *
     * @mbggenerated
     */
    private String successMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.error_code
     *
     * @mbggenerated
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.error_message
     *
     * @mbggenerated
     */
    private String errorMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.ext_param
     *
     * @mbggenerated
     */
    private String extParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.time_stamps
     *
     * @mbggenerated
     */
    private String timeStamps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.start_time
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.end_time
     *
     * @mbggenerated
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.elapse_time
     *
     * @mbggenerated
     */
    private String elapseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datacenter_merchant_push_log.push_result
     *
     * @mbggenerated
     */
    private String pushResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table datacenter_merchant_push_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.id
     *
     * @return the value of datacenter_merchant_push_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.id
     *
     * @param id the value for datacenter_merchant_push_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.merchant_id
     *
     * @return the value of datacenter_merchant_push_log.merchant_id
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.merchant_id
     *
     * @param merchantId the value for datacenter_merchant_push_log.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.biz_no
     *
     * @return the value of datacenter_merchant_push_log.biz_no
     *
     * @mbggenerated
     */
    public String getBizNo() {
        return bizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.biz_no
     *
     * @param bizNo the value for datacenter_merchant_push_log.biz_no
     *
     * @mbggenerated
     */
    public void setBizNo(String bizNo) {
        this.bizNo = bizNo == null ? null : bizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.org_biz_no
     *
     * @return the value of datacenter_merchant_push_log.org_biz_no
     *
     * @mbggenerated
     */
    public String getOrgBizNo() {
        return orgBizNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.org_biz_no
     *
     * @param orgBizNo the value for datacenter_merchant_push_log.org_biz_no
     *
     * @mbggenerated
     */
    public void setOrgBizNo(String orgBizNo) {
        this.orgBizNo = orgBizNo == null ? null : orgBizNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.push_data_size
     *
     * @return the value of datacenter_merchant_push_log.push_data_size
     *
     * @mbggenerated
     */
    public Long getPushDataSize() {
        return pushDataSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.push_data_size
     *
     * @param pushDataSize the value for datacenter_merchant_push_log.push_data_size
     *
     * @mbggenerated
     */
    public void setPushDataSize(Long pushDataSize) {
        this.pushDataSize = pushDataSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.success
     *
     * @return the value of datacenter_merchant_push_log.success
     *
     * @mbggenerated
     */
    public String getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.success
     *
     * @param success the value for datacenter_merchant_push_log.success
     *
     * @mbggenerated
     */
    public void setSuccess(String success) {
        this.success = success == null ? null : success.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.success_code
     *
     * @return the value of datacenter_merchant_push_log.success_code
     *
     * @mbggenerated
     */
    public String getSuccessCode() {
        return successCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.success_code
     *
     * @param successCode the value for datacenter_merchant_push_log.success_code
     *
     * @mbggenerated
     */
    public void setSuccessCode(String successCode) {
        this.successCode = successCode == null ? null : successCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.success_message
     *
     * @return the value of datacenter_merchant_push_log.success_message
     *
     * @mbggenerated
     */
    public String getSuccessMessage() {
        return successMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.success_message
     *
     * @param successMessage the value for datacenter_merchant_push_log.success_message
     *
     * @mbggenerated
     */
    public void setSuccessMessage(String successMessage) {
        this.successMessage = successMessage == null ? null : successMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.error_code
     *
     * @return the value of datacenter_merchant_push_log.error_code
     *
     * @mbggenerated
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.error_code
     *
     * @param errorCode the value for datacenter_merchant_push_log.error_code
     *
     * @mbggenerated
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode == null ? null : errorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.error_message
     *
     * @return the value of datacenter_merchant_push_log.error_message
     *
     * @mbggenerated
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.error_message
     *
     * @param errorMessage the value for datacenter_merchant_push_log.error_message
     *
     * @mbggenerated
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage == null ? null : errorMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.ext_param
     *
     * @return the value of datacenter_merchant_push_log.ext_param
     *
     * @mbggenerated
     */
    public String getExtParam() {
        return extParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.ext_param
     *
     * @param extParam the value for datacenter_merchant_push_log.ext_param
     *
     * @mbggenerated
     */
    public void setExtParam(String extParam) {
        this.extParam = extParam == null ? null : extParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.time_stamps
     *
     * @return the value of datacenter_merchant_push_log.time_stamps
     *
     * @mbggenerated
     */
    public String getTimeStamps() {
        return timeStamps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.time_stamps
     *
     * @param timeStamps the value for datacenter_merchant_push_log.time_stamps
     *
     * @mbggenerated
     */
    public void setTimeStamps(String timeStamps) {
        this.timeStamps = timeStamps == null ? null : timeStamps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.gmt_modified
     *
     * @return the value of datacenter_merchant_push_log.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.gmt_modified
     *
     * @param gmtModified the value for datacenter_merchant_push_log.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.gmt_create
     *
     * @return the value of datacenter_merchant_push_log.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.gmt_create
     *
     * @param gmtCreate the value for datacenter_merchant_push_log.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.start_time
     *
     * @return the value of datacenter_merchant_push_log.start_time
     *
     * @mbggenerated
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.start_time
     *
     * @param startTime the value for datacenter_merchant_push_log.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.end_time
     *
     * @return the value of datacenter_merchant_push_log.end_time
     *
     * @mbggenerated
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.end_time
     *
     * @param endTime the value for datacenter_merchant_push_log.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.elapse_time
     *
     * @return the value of datacenter_merchant_push_log.elapse_time
     *
     * @mbggenerated
     */
    public String getElapseTime() {
        return elapseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.elapse_time
     *
     * @param elapseTime the value for datacenter_merchant_push_log.elapse_time
     *
     * @mbggenerated
     */
    public void setElapseTime(String elapseTime) {
        this.elapseTime = elapseTime == null ? null : elapseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datacenter_merchant_push_log.push_result
     *
     * @return the value of datacenter_merchant_push_log.push_result
     *
     * @mbggenerated
     */
    public String getPushResult() {
        return pushResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datacenter_merchant_push_log.push_result
     *
     * @param pushResult the value for datacenter_merchant_push_log.push_result
     *
     * @mbggenerated
     */
    public void setPushResult(String pushResult) {
        this.pushResult = pushResult == null ? null : pushResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datacenter_merchant_push_log
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MerchantPushLog other = (MerchantPushLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMerchantId() == null ? other.getMerchantId() == null : this.getMerchantId().equals(other.getMerchantId()))
            && (this.getBizNo() == null ? other.getBizNo() == null : this.getBizNo().equals(other.getBizNo()))
            && (this.getOrgBizNo() == null ? other.getOrgBizNo() == null : this.getOrgBizNo().equals(other.getOrgBizNo()))
            && (this.getPushDataSize() == null ? other.getPushDataSize() == null : this.getPushDataSize().equals(other.getPushDataSize()))
            && (this.getSuccess() == null ? other.getSuccess() == null : this.getSuccess().equals(other.getSuccess()))
            && (this.getSuccessCode() == null ? other.getSuccessCode() == null : this.getSuccessCode().equals(other.getSuccessCode()))
            && (this.getSuccessMessage() == null ? other.getSuccessMessage() == null : this.getSuccessMessage().equals(other.getSuccessMessage()))
            && (this.getErrorCode() == null ? other.getErrorCode() == null : this.getErrorCode().equals(other.getErrorCode()))
            && (this.getErrorMessage() == null ? other.getErrorMessage() == null : this.getErrorMessage().equals(other.getErrorMessage()))
            && (this.getExtParam() == null ? other.getExtParam() == null : this.getExtParam().equals(other.getExtParam()))
            && (this.getTimeStamps() == null ? other.getTimeStamps() == null : this.getTimeStamps().equals(other.getTimeStamps()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getElapseTime() == null ? other.getElapseTime() == null : this.getElapseTime().equals(other.getElapseTime()))
            && (this.getPushResult() == null ? other.getPushResult() == null : this.getPushResult().equals(other.getPushResult()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datacenter_merchant_push_log
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMerchantId() == null) ? 0 : getMerchantId().hashCode());
        result = prime * result + ((getBizNo() == null) ? 0 : getBizNo().hashCode());
        result = prime * result + ((getOrgBizNo() == null) ? 0 : getOrgBizNo().hashCode());
        result = prime * result + ((getPushDataSize() == null) ? 0 : getPushDataSize().hashCode());
        result = prime * result + ((getSuccess() == null) ? 0 : getSuccess().hashCode());
        result = prime * result + ((getSuccessCode() == null) ? 0 : getSuccessCode().hashCode());
        result = prime * result + ((getSuccessMessage() == null) ? 0 : getSuccessMessage().hashCode());
        result = prime * result + ((getErrorCode() == null) ? 0 : getErrorCode().hashCode());
        result = prime * result + ((getErrorMessage() == null) ? 0 : getErrorMessage().hashCode());
        result = prime * result + ((getExtParam() == null) ? 0 : getExtParam().hashCode());
        result = prime * result + ((getTimeStamps() == null) ? 0 : getTimeStamps().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getElapseTime() == null) ? 0 : getElapseTime().hashCode());
        result = prime * result + ((getPushResult() == null) ? 0 : getPushResult().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datacenter_merchant_push_log
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", merchantId=").append(merchantId);
        sb.append(", bizNo=").append(bizNo);
        sb.append(", orgBizNo=").append(orgBizNo);
        sb.append(", pushDataSize=").append(pushDataSize);
        sb.append(", success=").append(success);
        sb.append(", successCode=").append(successCode);
        sb.append(", successMessage=").append(successMessage);
        sb.append(", errorCode=").append(errorCode);
        sb.append(", errorMessage=").append(errorMessage);
        sb.append(", extParam=").append(extParam);
        sb.append(", timeStamps=").append(timeStamps);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", elapseTime=").append(elapseTime);
        sb.append(", pushResult=").append(pushResult);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}